name: Build APK

on:
  workflow_dispatch:  # 手动触发构建

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout CherryHQ/cherry-studio-app
        uses: actions/checkout@v4
        with:
          repository: CherryHQ/cherry-studio-app # 指定要克隆的仓库
          ref: main           # 指定要克隆的分支
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "${HOME}/.bun/bin" >> $GITHUB_PATH

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Install dependencies
        run: bun install

      - name: Build APK
        run: eas build --platform android --non-interactive --local

      - name: Upload APK artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: apk-build-output
          path: |
            dist
            ./**/build/**/outputs/**/*.apk
